### PR TITLE
feat: read processor settings from root of s3 dir

### LINKED ISSUE #8: Read settings from root of s3 processing dir
The easiest place to read settings from is the S3 processing dir root, rather than having to upload custom labmda zips. The settings file should be located there, and to handle occasions where CloudFormation can't return the name of the Redis host, `redis_name` should be a valid option that describes an AWS Elasticache cluster, which the processor can locate and find a host for.

### PR DESCRIPTION
**Pull request by bbangert**
Changes where the config is read from to the root of the S3 dir that
is having its messages processed. This enables easier deployments in
multi-deployed scenarios.

Makefile updates to reduce the size of the generated lambda function
substantially from ~28 MB to ~4 MB.

Removed push_messages dependency as the single dynamodb call to make
was more efficient to encode directly as part of the substantial
reduction in lambda function package size.

Closes #8 

@jrconlin r?

### CODE REVIEW

**Comment by jrconlin** [comment]
r+

**Comment by bbangert** [comment]
Unfortunately can't merge yet,  it no longer works on AWS.

**Comment by bbangert** [comment]
Ok, now it works on AWS too.

**Comment by jrconlin** [comment]
r+

**Pull request merged**
